# Site settings
title: Noisy Tenants
email: info@noisytenants.com
description: > # this means to ignore newlines until "baseurl:"
  The Leasing Office - Your Community Agency
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nickmtchl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
port: 4000
twitter_handle: noisytenants
instagram_handle: noisytenants
facebook_handle: noisytenants


# Build settings
markdown: kramdown
permalink: /post/:title/

# Setup Collections
collections:
  work:
    output: true
    permalink: /work/:title/

  press:
    output: false

  team:
    output: false

  bsbtracker:
    output: false

  docs:
    output: false

# Default Settings for Collections
defaults:
  -
    scope:
      path: ""
      type: "bsbtracker" # a collection in your site, in plural form
    values:
      title: "1-week-012918-020218"
      week: "1"
      week-start: "Jan 29, 2018"
      week-end: "Feb 02, 2018"
      day1:
          date: "01/29"
          status: "late"
      day2:
          date: "01/30"
          status: "ontime"
      day3:
          date: "01/31"
          status: "late"
      day4:
          date: "02/01"
          status: "noshow"
      day5:
          date: "02/02"
          status: "ontime"

  -
    scope:
      path: ""
      type: "press" # a collection in your site, in plural form
    values:
      publication: "The Baltimore Sun"
      external_link: "http://www.google.com"


# Social Media


# Extra Misc Stuff
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
