# Site settings
title: Noisy Tenants
email: info@noisytenants.com
description: > # this means to ignore newlines until "baseurl:"
  The Leasing Office - Your Community Agency
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://noisytenants.svncrwns.com" # the base hostname & protocol for your site, e.g. http://example.com
port: 4000
twitter_username: noisytenants
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /post/:title/


collections:
  work:
    output: true
    permalink: /work/:title/


# Extra Misc Stuff
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
