---
title: Noisy Tenants
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: false
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:title/"
email: info@noisytenants.com
description: 'The Leasing Office - Your Community Agency

'
baseurl: ''
url: http://nickmtchl.github.io
port: 4000
twitter_username: noisytenants
github_username: 
markdown: kramdown
permalink: "/post/:title/"
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
