---
title: Noisy Tenants
timezone: UTC
collections:
  bsbtracker:
    title: Bsbtracker
    output: false
  docs:
    title: Docs
    output: false
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: false
  team:
    title: Team
    output: false
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:title/"
defaults:
- scope:
    path: ''
    type: bsbtracker
  values:
    title: 1-week-012918-020218
    week: '1'
    week-start: Jan 29, 2018
    week-end: Feb 02, 2018
    day1:
      date: 01/29
      status: late
    day2:
      date: 01/30
      status: ontime
    day3:
      date: 01/31
      status: late
    day4:
      date: 02/01
      status: noshow
    day5:
      date: 02/02
      status: ontime
- scope:
    path: ''
    type: press
  values:
    publication: The Baltimore Sun
    external_link: http://www.google.com
email: info@noisytenants.com
description: 'The Leasing Office - Your Community Agency

'
baseurl: ''
url: http://nickmtchl.github.io
port: 4000
twitter_handle: noisytenants
instagram_handle: noisytenants
facebook_handle: noisytenants
markdown: kramdown
permalink: "/post/:title/"
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
